# Source: traderlite/templates/stock-quote.yaml
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: acmetrader-stock-quote-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app: acmetrader-stock-quote
